language: python

python:
  - 3.6


install:
  - pip install coveralls

script:

  - coverage run --source=paragraph_generator setup.py test
  - coverage report -m
  # Run the doctests

after_success:
  - coveralls
